parameters:
- name: 'vmImage'
  default: 'Default'
  type: string
- name: 'samplestring'
  default: 'Hello'
  type: string

jobs:
- job: Build
  pool:
    name: ${{ parameters.vmImage }}

  steps:
  - bash: |
      echo $(ui_variable)
      
  - task: greetTask@1
      samplestring: ${{ parameters.samplestring }}
