parameters:
- name: 'vmImage'
  default: 'Default'
  type: string

jobs:
- job: Build
  pool:
    name: ${{ parameters.vmImage }}

  steps:
  - bash: |
      echo $(ui_variable)
      
  - task: greetTask@1
      # inputs:
      #   samplestring: 'public'
